# Performance and Code Complexity Comparison
```{r setup_pkgs}
library(ComplexHeatmap)
library(pheatmap)
library(gplots)
library(ggalign)
```


## A 
```{r setup_fn}
bench_heatmap <- function(matrix) {
    bench::mark(
        "heatmap()" = {
            pdf(NULL)
            heatmap(matrix, Rowv = NA, Colv = NA)
            dev.off()
            NULL
        },
        # gplots is very very slow
        # "gplots::heatmap.2()" = {
        #     pdf(NULL)
        #     heatmap.2(matrix, dendrogram = "none", trace = "none")
        #     dev.off()
        #     NULL
        # },
        "ComplexHeatmap::Heatmap()" = {
            pdf(NULL)
            draw(Heatmap(matrix,
                cluster_rows = FALSE, cluster_columns = FALSE,
                use_raster = TRUE
            ))
            dev.off()
            NULL
        },
        "pheatmap::pheatmap()" = {
            pdf(NULL)
            pheatmap(matrix, cluster_rows = FALSE, cluster_cols = FALSE)
            dev.off()
            NULL
        },
        "ggalign()" = {
            pdf(NULL)
            print(ggheatmap(matrix, filling = "raster"))
            dev.off()
            NULL
        },
        memory = FALSE,
        iterations = 1
    )
}

set.seed(123)
heatmap_bench <- lapply(c(1000, 2000, 5000, 10000), function(n) {
    mat <- matrix(rnorm(n * n), nrow = n)
    dplyr::mutate(bench_heatmap(mat), size = sprintf("%dx%d", n, n))
})
heatmap_bench_bar <- dplyr::bind_rows(heatmap_bench) |>
    ggplot(
        aes(forcats::fct_inorder(size), median,
            fill = forcats::fct_inorder(as.character(expression))
        )
    ) +
    geom_bar(stat = "identity", position = position_dodge()) +
    scale_fill_brewer(palette = "Dark2", name = NULL) +
    labs(x = NULL, y = "Timing (Seconds)") +
    theme_bw() +
    theme(legend.position = "inside", legend.position.inside = c(0.2, 0.5))
ggsave("output/FigureS5A.pdf",
    plot = heatmap_bench_bar, width = 9, height = 8,
    family = "Helvetica"
)
```

## B

```{r}
ggalign <- cyclocomp::cyclocomp_package("ggalign")
complexheatmap <- cyclocomp::cyclocomp_package("ComplexHeatmap")
ggplot2 <- cyclocomp::cyclocomp_package("ggplot2")
data <- list(
    ggalign = ggalign,
    ComplexHeatmap = complexheatmap,
    ggplot2 = ggplot2
)
data <- dplyr::bind_rows(data, .id = "package")
```


```{r}
FigureS5B <- data |>
    dplyr::summarize(cyclocomp = mean(cyclocomp), .by = package) |>
    ggplot() +
    geom_bar(aes(package, cyclocomp, fill = package), stat = "identity") +
    scale_fill_brewer(palette = "Dark2", guide = "none") +
    xlab(NULL) +
    ylab("Mean Cyclomatic Complexity") +
    theme_bw()

FigureS5C <- data |>
    dplyr::summarize(cyclocomp = max(cyclocomp), .by = package) |>
    ggplot() +
    geom_bar(aes(package, cyclocomp, fill = package), stat = "identity") +
    scale_fill_brewer(palette = "Dark2", guide = "none") +
    xlab(NULL) +
    ylab("Max Cyclomatic Complexity") +
    theme_bw()

FigureS5D <- data |>
    dplyr::filter(cyclocomp >= 10) |>
    ggplot() +
    geom_bar(aes(package, after_stat(count), fill = package)) +
    scale_fill_brewer(palette = "Dark2", guide = "none") +
    xlab(NULL) +
    ylab("Number of Functions with Complexity >= 10") +
    theme_bw()

ggsave(
    "output/FigureS5B.pdf",
    plot = ggalign::align_plots(FigureS5B, FigureS5C, FigureS5D, nrow = 1L),
    width = 10, height = 6
)
```
